sh alexnetFe_proceedTrain.sh
sh alexnetFe_extractFeatures.sh
sh alexnetFe_simpleEnc_simpleDec_train.sh
sh alexnetFe_simpleEnc_simpleDec_test.sh
sh alexnetFe_simpleEnc_simpleDec_e2e_finetuning.sh
sh alexnetFe_simpleEnc_simpleDec_e2e_test.sh